In [5]:
import torch

In [6]:
def create_frustum(depth_cfg, input_size, downsample):
    """Generate the frustum template for each image.

    Args:
        depth_cfg (tuple(float)): Config of grid alone depth axis in format
            of (lower_bound, upper_bound, interval).
        input_size (tuple(int)): Size of input images in format of (height,
            width).
        downsample (int): Down sample scale factor from the input size to
            the feature size.
    """
    H_in, W_in = input_size
    H_feat, W_feat = H_in // downsample, W_in // downsample
    d = torch.arange(*depth_cfg, dtype=torch.float)\
        .view(-1, 1, 1).expand(-1, H_feat, W_feat)
    D = d.shape[0]
    x = torch.linspace(0, W_in - 1, W_feat,  dtype=torch.float)\
        .view(1, 1, W_feat).expand(D, H_feat, W_feat)
    y = torch.linspace(0, H_in - 1, H_feat,  dtype=torch.float)\
        .view(1, H_feat, 1).expand(D, H_feat, W_feat)

    # D x H x W x 3
    frustum = torch.stack((x, y, d), -1)  #frustum[k,v_f,u_f]->(u, v, d),  下采样后特征图
    return frustum

In [7]:
frustum = create_frustum([1.0, 60.0, 1.0], [256, 704], 16)

In [9]:
print(frustum[32][14][32])
print(frustum[12][4][12])
print(frustum[2][13][19])
print(frustum[54][1][43])



tensor([523.1628, 238.0000,  33.0000])
tensor([196.1860,  68.0000,  13.0000])
tensor([310.6279, 221.0000,   3.0000])
tensor([703.,  17.,  55.])


In [18]:
a = torch.arange(1, 10, 1,dtype=torch.float).view(3,3)
print(a)
b = torch.tensor([4,5,1.]).unsqueeze(-1)
print(b.size())
c = a.matmul(b)
print(c)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.Size([3, 1])
tensor([[17.],
        [47.],
        [77.]])
